version: '2'

services:
  popolo-db:
    image: mongo
    container_name: "popolo-db"
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  popolo-api:
    build: .
    container_name: "popolo-api"
    depends_on:
      - popolo-db
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
